### ISSUE TITLE
在HA上运行，连接frps正常，访问域名报错：400: Bad Request

### ISSUE THREAD

**Issue by waxgourd-ha** [huxiaoxu2019/hass-addon-frp-client#11]
![image](https://github.com/huxiaoxu2019/hass-addon-frp-client/assets/152601480/b9b6437d-5aff-49a4-9872-4ad90577e230)

**Comment by huxiaoxu2019** [comment]
@waxgourd-ha would you please be more specific for this issue, I'm happy to fix that~

**Comment by wileon994** [comment]
Hi, I am facing the same problem. This is my configuration.
![image](https://github.com/huxiaoxu2019/hass-addon-frp-client/assets/65838018/e654b409-8bb6-4cf8-9ed8-65e9afbb4bc2)
![image](https://github.com/huxiaoxu2019/hass-addon-frp-client/assets/65838018/d879a565-a7c8-4624-995c-c73c12523dd3)

**Comment by wileon994** [comment]
![image](https://github.com/huxiaoxu2019/hass-addon-frp-client/assets/65838018/92c8bbb6-786d-4d6e-bfa4-d73e3982182c)
And this is the local frp dashboard, the dashboard on the frps also works well.
I also tried using the IP address like xxx.xxx.xxx.xxx:8123, also 400 Bad Request.

**Comment by huxiaoxu2019** [comment]
Thanks for the detailed information, I tried to reproduce the error `400: Bad Request`, and found that you need to add this configuration in your `configuration.yaml` shown as the picture below. I believe that should be mentioned in the `Installation` section on Readme.

<img width="465" alt="Screenshot 2024-03-15 at 12 44 47" src="https://github.com/huxiaoxu2019/hass-addon-frp-client/assets/5491423/e8d6ee55-9796-425f-8b48-2b6039950260">

_You can edit that configuration by File Editor add-on_

```
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
```

It's better to change `0.0.0.0/0` to your proxy server IP.

**Comment by huxiaoxu2019** [comment]
⬆️  @wileon994 cc @waxgourd-ha

**Comment by wileon994** [comment]
Sorry to miss the instructions, it works well right now. 
Thanks for your attention!
