### ISSUE TITLE
400: Bad Request

### ISSUE THREAD

**Issue by wileon994** [huxiaoxu2019/hass-addon-frp-client#12]
@huxiaoxu2019  Hi, I have posted the details of this issue to this closed issue, pls take a look! Thanks.
[在HA上运行，连接frps正常，访问域名报错：400: Bad Request](https://github.com/huxiaoxu2019/hass-addon-frp-client/issues/11#issuecomment-1994801946)

**Comment by huxiaoxu2019** [comment]
> @huxiaoxu2019 Hi, I have posted the details of this issue to this closed issue, pls take a look! Thanks. [在HA上运行，连接frps正常，访问域名报错：400: Bad Request](https://github.com/huxiaoxu2019/hass-addon-frp-client/issues/11#issuecomment-1994801946)

Thanks, let me take a look now
