### ISSUE TITLE
frp版本

### ISSUE THREAD

**Issue by Trace-star** [huxiaoxu2019/hass-addon-frp-client#15]
你好，我两年已经部署了frps服务端。用的是frp 0.20.0。之前用的是Hass，可以直接自己安装。今年转到Hass-OS后，一直没有很好的解决方案。看着你这个不错。是否可以有偿做一个frp0.20.0的

**Comment by huxiaoxu2019** [comment]
Hey @Trace-star 
Thank you for opening this issue. First, I want to confirm that this is a critical requirement. Why do we need to stick with the old version (0.20.0)?
